framework:
    router:
        #utf8: true
        # Set the routing generator behaviour see this:
        # https://symfony.com/doc/current/reference/configuration/framework.html#strict-requirements
        strict_requirements: ~
        # because it is defined ~ it will look in de dev, prod and test directories here.

        # Enable utf8 support in routes see this:
        # https://symfony.com/blog/new-in-symfony-3-2-unicode-routing-support