framework:
    validation:
        enabled: true
        enable_annotations: false
        email_validation_mode: html5
        translation_domain: validators
        mapping:
          paths:
            - '%kernel.project_dir%/config/validator/'


