vich_uploader:
  db_driver: orm

  mappings:
    game_scenario:
      upload_destination: '%kernel.project_dir%/public/uploads/scenario'
      namer: Vich\UploaderBundle\Naming\OrignameNamer
  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
