#
#                                The Desk CriSim - Continues Integration Suite
#---------------------------------------------------------------------------------------------------------------------
# This file contains the configuration of our continues integration suite used to check new commits, merges and pull
# requests. When you submit a change to the repository on github it will run the configure scrips, if there are
# problems with the submitted code. It will notify the user by showing a error message and placing a red cross next to
# to the commit hash. Usually this check is performed and finished before merging so you can choose if you want to
# submit code that breaks the CI. Because our master branch is protected and moderated, It won't accept any changes
# that break testing, as it should!
#
# Items that are tested:
#   - Unit tests defined in
#
#
language: php
sudo: false

cache:
  directories:
  - $HOME/.composer/cache/files
  - ./bin/.phpunit

env:
  global:
  - SYMFONY_PHPUNIT_DIR=./bin/.phpunit

matrix:
  fast_finish: true
  include:
  - php: 7.2
  - php: nightly
  allow_failures:
  - php: nightly

before_install:
- '[[ "$TRAVIS_PHP_VERSION" == "nightly" ]] || phpenv config-rm xdebug.ini'
- composer self-update

install:
- composer install
- ./bin/phpunit install

script:
- ./bin/phpunit
# this checks that the YAML config files contain no syntax errors
- ./bin/console lint:yaml config
# this checks that the Twig template files contain no syntax errors
- ./bin/console lint:twig templates
# this checks that the XLIFF translations contain no syntax errors
- ./bin/console lint:xliff translations
# this checks that the application doesn't use dependencies with known security vulnerabilities
- ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock
# this checks that the composer.json and composer.lock files are valid
- composer validate --strict
# this checks that Doctrine's mapping configurations are valid
- ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction