###############################################################################
#                   The Docker - Composer configuration file                  #
###############################################################################
version: "3.1"
services:
  # Add a database server for storing the application data.
  mysql:
    # I chose mysql >= 5.7 because they added the json field type in this version.
    image: mysql:5.7
    container_name: desk-crisim-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=DeskCriSim
      - MYSQL_USER=crisim-app
      - MYSQL_PASSWORD=crisim-app-password
    ports:
      - "8082:3306"

  # Add nginx for handling incoming web requests and passing dynamic requests to php.
  webserver:
    image: nginx:alpine
    container_name: desk-crisim-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  # Add php-fpm for processing the application's dynamic content.
  php-fpm:
    build: phpdocker/php-fpm
    container_name: desk-crisim-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

