#
# Authentication and Authorization routes.
#
# This file contains all routes for authenticating users.
#
authentication_login:
    path:
        nl: /inloggen
        en: /{_locale}/login
        fy: /{_locale}/
    controller: App\Controller\Authentication\LoginController::index
