#
# Authentication and Authorization routes.
#
# This file contains all routes for authenticating users.
#
authentication_login:
  path: /{_locale}/login
  controller: App\Controller\StudentController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'
