#
# Student routes.
#
# This file contains all routes to the students accessible pages.
#
student_index:
  path: /{_locale}/student
  controller: App\Controller\Student\Game\ActionController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

student_actions:
  path: /{_locale}/student/actions
  controller: App\Controller\Student\Game\ActionController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

student_InfoFeed:
  path: /{_locale}/student/infofeed
  controller: App\Controller\Student\Game\InfoFeedController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

student_chat:
  path: /{_locale}/student/Chat
  controller: App\Controller\Student\Chat\ChatController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'