#
# Student routes.
#
# This file contains all routes to the students accessible pages.
#
student_index:
    path:
        nl: /student
        en: /{_locale}/student
        fy: /{_locale}/studint
    controller: App\Controller\Student\Game\ActionController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

student_actions:
    path:
        nl: /student/handelingen
        en: /{_locale}/student/actions
        fy: /{_locale}/studint/aksjes
    controller: App\Controller\Student\Game\ActionController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

student_InfoFeed:
    path:
        nl: /student/info feed
        en: /{_locale}/student/info feed
        fy: /{_locale}/studint/info feed
    controller: App\Controller\Student\Game\InfoFeedController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

student_chat:
    path:
        nl: /student/chat
        en: /{_locale}/student/chat
        fy: /{_locale}/studint/chat
    controller: App\Controller\Student\Chat\ChatController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'