#
# Teacher routes.
#
# This file contains all routes to the teacher accessible pages.
#
teacher_index:
  path: /{_locale}/teacher
  controller: App\Controller\TeacherController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'
