#
# Teacher routes.
#
# This file contains all routes to the Teacher accessible pages.
#
teacher_index:
    path:
        nl: /docent
        en: /{_locale}/teacher
        fy: /{_locale}/leeraar
    controller: App\Controller\Teacher\HomeController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

#
# Teacher::chat routes.
#
teacher_chatMonitor:
    path:
        nl: /docent/chat monitor
        en: /{_locale}/teacher/chat monitor
        fy: /{_locale}/leeraar/chat monitor
    controller: App\Controller\Teacher\Chat\ChatMonitorController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

#
# Teacher::game routes.
#
teacher_participators:
    path:
        nl: /docent/participant
        en: /{_locale}/teacher/participant
        fy: /{_locale}/leeraar/dielnimmer
    controller: App\Controller\Teacher\Game\AddParticipatorsController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

teacher_create_event:
    path:
        nl: /docent/creëer evenement
        en: /{_locale}/teacher/create event
        fy: /{_locale}/leeraar/In event meitsje
    options:
        utf8: true
    controller: App\Controller\Teacher\Game\CreateEventController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

teacher_create_session:
    path:
        nl: /docent/Sessie creëren
        en: /{_locale}/teacher/Create a session
        fy: /{_locale}/leeraar/In sesje meitsje
    options:
        utf8: true
    controller: App\Controller\Teacher\Game\CreateSessionController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

teacher_show_statistics:
    path:
        nl: /docent/Statistieken weergeven
        en: /{_locale}/teacher/View statistics
        fy: /{_locale}/leeraar/Besjoch statistyk
    controller: App\Controller\Teacher\Game\ShowStatisticsController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

#
# Teacher::game - Scenario routes.
#
upload_scenario:
    path:
        nl: /docent/Scenario Uploaden
        en: /{_locale}/teacher/Upload Scenario
        fy: /{_locale}/leeraar/Upload Szenario
    controller: App\Controller\Teacher\Game\UploadGameScenarioController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

teacher_assign_points:
    path:
        nl: /docent/Punten toekennen
        en: /{_locale}/teacher/Award points
        fy: /{_locale}/leeraar/Awardpunten
    controller: App\Controller\Teacher\Game\AssignPointsController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

teacher_start_scenario:
    path:
        nl: /docent/Scenario Starten
        en: /{_locale}/teacher/Start scenario
        fy: /{_locale}/leeraar/Begjin senario
    controller: App\Controller\Teacher\Game\StartGameController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'

#
# Observer (Teacher) routes.
#
# This file contains all routes to the Observer accessible pages. The logger
# is a Teacher that walks around during a Game session and can add additional
# information to the students behaviour during the Game.
#
logger_index:
    path:
        nl: /docent/Toezichthouder
        en: /{_locale}/teacher/Supervisor
        fy: /{_locale}/leeraar/Supervisor
    controller: App\Controller\AdminController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'