#
# Teacher routes.
#
# This file contains all routes to the Teacher accessible pages.
#
teacher_index:
  path: /{_locale}/teacher
  controller: App\Controller\Teacher\Controller::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

teacher_participators:
  path: /{_locale}/teacher/participators
  controller: App\Controller\TeacherController::participators
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

teacher_chatMonitor:
  path: /{_locale}/teacher/chatmonitor
  controller: App\Controller\TeacherController::chatMonitor
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

teacher_loadEvent:
  path: /{_locale}/teacher/loadEvent
  controller: App\Controller\TeacherController::loadEvent
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

teacher_createSession:
  path: /{_locale}/teacher/createSession
  controller: App\Controller\CreateSessionController::new
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

teacher_showStatistics:
  path: /{_locale}/teacher/showStatistics
  controller: App\Controller\TeacherController::showStatistics
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

teacher_uploadSenario:
  path: /{_locale}/teacher/uploadScenario
  controller: App\Controller\UploadScenarioController::new
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

teacher_assignPoints:
  path: /{_locale}/teacher/assignPoints
  controller: App\Controller\TeacherController::assignPoints
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

teacher_startSenario:
  path: /{_locale}/teacher/startSenario
  controller: App\Controller\TeacherController::startScenario
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

#
# Observer (Teacher) routes.
#
# This file contains all routes to the Observer accessible pages. The logger
# is a Teacher that walks around during a Game session and can add additional
# information to the students behaviour during the Game.
#
logger_index:
  path: /{_locale}/logger
  controller: App\Controller\AdminController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'