#
# Teacher routes.
#
# This file contains all routes to the Teacher accessible pages.
#
teacher_index:
  path: /{_locale}/teacher
  controller: App\Controller\Teacher\HomeController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

#
# Teacher::chat routes.
#
teacher_chatMonitor:
  path: /{_locale}/teacher/chatmonitor
  controller: App\Controller\Teacher\Chat\ChatMonitorController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

#
# Teacher::game routes.
#
teacher_participators:
  path: /{_locale}/teacher/participators
  controller: App\Controller\Teacher\Game\AddParticipatorsController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

teacher_create_event:
  path: /{_locale}/teacher/create-event
  controller: App\Controller\Teacher\Game\CreateEventController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

teacher_create_session:
  path: /{_locale}/teacher/create-session
  controller: App\Controller\Teacher\Game\CreateSessionController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

teacher_show_statistics:
  path: /{_locale}/teacher/showStatistics
  controller: App\Controller\Teacher\Game\ShowStatisticsController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

#
# Teacher::game - Scenario routes.
#
upload_scenario:
  path: /{_locale}/teacher/upload-scenario
  controller: App\Controller\Teacher\Game\UploadGameScenarioController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

teacher_assign_points:
  path: /{_locale}/teacher/assign-points
  controller: App\Controller\Teacher\Game\AssignPointsController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

teacher_start_scenario:
  path: /{_locale}/teacher/start-scenario
  controller: App\Controller\Teacher\Game\StartGameController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

#
# Observer (Teacher) routes.
#
# This file contains all routes to the Observer accessible pages. The logger
# is a Teacher that walks around during a Game session and can add additional
# information to the students behaviour during the Game.
#
logger_index:
  path: /{_locale}/logger
  controller: App\Controller\AdminController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'