#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /{_locale}/teacher
  controller: App\Controller\TeacherController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'
