_translation_webui:
  resource: "@TranslationBundle/Resources/config/routing_webui.yml"
  prefix:  /{_locale}/administrator

_translation_profiler:
  resource: '@TranslationBundle/Resources/config/routing_symfony_profiler.yml'
