#
# This validators configuration file contains the validation constraints for a user.
#
# Author: Joris Rietveld <jorisrietveld@gmail.com>
# Date: 18-12-2018 15:00
# Licence: GPLv3 - General Public Licence version 3
#
