#
# Global routes configuration.
#
# This file contains all routes for the application. It also includes route configuration resources in from the
# routes/ directory. These files bundle routes that are related to each other.
#

#
# All unauthorized index (homepage) routes.
#
homepage_unlocalized:
  path: /
  controller: App\Controller\IndexController::index

homepage:
  path: /{_locale}
  controller: App\Controller\IndexController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

#
# All administrator related routes.
#
admin_index:
  path: /{_locale}/admin
  controller: App\Controller\AdminController::index
  requirements:
    _locale: '%app.locales%'
  defaults:
    _locale: '%locale%'

#
# All teacher related routes.
#
teacher:
  resource: 'routes/teacher.yaml'

#
# All student related routes.
#
student:
  resource: 'routes/student.yml'

#
# All routs related to authentication and authorization.
#
authentication:
  resource: 'routes/authentication.yml'
