#
# Global routes configuration.
#
# This file contains all routes for the application. It also includes route configuration resources in from the
# routes/ directory. These files bundle routes that are related to each other.
#
homepage:
    path: /{_locale}
    controller: App\Controller\WelcomeController::index
    requirements:
        _locale: '%app.locales%'
    defaults:
        _locale: '%locale%'